name: Setup Python UV
description: Checkout, install python and uv

runs:
  using: 'composite'
  steps:

    - name: install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.9.5"
        enable-cache: true

    - uses: actions/setup-python@v6
      with:
        python-version: "3.13"

    - name: uv sync
      run: uv sync
      shell: bash
