# Infos on current github runners:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#about-github-hosted-runners

name: Build
on: [push]

jobs:
  build:
    name: Build packages
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install briefcase
        shell: bash -l {0}
        run: pip3 install briefcase
      - name: Run build tools
        shell: bash -l {0}
        run: python3 build.py

      - name: Draft release
        uses: ncipollo/release-action@v1
        with:
          body: See [CHANGELOG](https://github.com/dynobo/normcap/blob/main/CHANGELOG.md) for details.
          artifacts: "macOS/*.dmg,linux/*.AppImage,windows\\*.msi"
          allowUpdates: true
          artifactErrorsFailBuild: false
          draft: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
